title: Shreeya Ambre
logo: /PXL_20240501_233302491.PORTRAIT.ORIGINAL~2.jpg


address: Boston, MA 02120
contact: (857) 396-6403
mail1: shreeyaambre@outlook.com 
mail2: ambre.s@northeastern.edu 
#description: Data Analyst
show_downloads: true
theme: jekyll-theme-minimal
