title: Shreeya Ambre
logo: /assets/PXL_20240501_233302491.PORTRAIT.ORIGINAL~2.jpg

description: Boston, MA 02120
(857) 396-6403
shreeyaambre@outlook.com 
ambre.s@northeastern.edu 
#show_downloads: true
theme: jekyll-theme-minimal
